snapshot of project "td_lib", label t20201208

diff --git a/support/ins_hdr b/support/ins_hdr
--- a/support/ins_hdr
+++ b/support/ins_hdr
@@ -1,58 +1,53 @@
 #! /bin/sh
-# $Id: ins_hdr,v 12.2 2010/07/02 10:50:12 tom Exp $
+# $Id: ins_hdr,v 12.3 2020/12/08 01:01:32 tom Exp $
 #
 # This script is used to adjust includes for header files that reside in a
 # subdirectory of /usr/include, etc.
 
-if test $# = 0 ; then
-	echo '? No INSTALL program given'
+failed() {
+	echo "? $*" >&2
 	exit 1
-fi
+}
+
+test $# = 0 && failed 'No INSTALL program given'
 PRG="$1"
 shift
 
-if test $# = 0 ; then
-	echo '? No DESTDIR given'
-	exit 1
-fi
-DESTDIR=$1
-shift
-
-if test $# = 0 ; then
-	echo '? No DESTINATION given'
-	exit 1
-fi
+test $# = 0 && failed 'No DESTINATION given'
 DST=$1
 shift
 
-if test $# = 0 ; then
-	echo '? No SOURCE given'
-	exit 1
-fi
+test $# = 0 && failed 'No SOURCEDIR given'
+SOURCEDIR=$1
+shift
+
+test $# = 0 && failed 'No SOURCES given'
 
 SED=${TMPDIR-/tmp}/sed$$
-rm -f $SED
-trap "rm -f $SED" 0 1 2 5 15
+rm -f "$SED"
+trap 'rm -f "$SED"' EXIT INT QUIT TERM HUP
 
-END=`basename $DST`
-for SRC in $*
+END=`basename "$DST"`
+for SRC in "$@"
 do
-	echo "s/<$SRC>/<$END\/$SRC>/" >> $SED
+	echo "s/<$SRC>/<$END\/$SRC>/" >> "$SED"
 done
 
-for SRC in $*
+for SRC in "$@"
 do
-	echo installing $SRC in $DST
+	echo "installing $SRC in $DST"
 	case $DST in
 	/*/include/*)
-		src=`basename $SRC`
+		src=`basename "$SRC"`
 		TMP=${TMPDIR-/tmp}/$src
-		sed -f $SED include/$src > $TMP
-		eval $PRG $TMP $DST
-		rm -f $TMP
+		src="include/$src"
+		test -f "$src" || src="$SOURCEDIR/$src"
+		sed -f "$SED" "$src" > "$TMP"
+		eval "$PRG" "$TMP" "$DST"
+		rm -f "$TMP"
 		;;
 	*)
-		eval $PRG $SRC $DST
+		eval "$PRG" "$SRC" "$DST"
 		;;
 	esac
 done
diff --git a/support/ins_mak b/support/ins_mak
--- a/support/ins_mak
+++ b/support/ins_mak
@@ -1,69 +1,62 @@
 #! /bin/sh
-# $Id: ins_mak,v 12.6 2015/07/04 15:05:05 tom Exp $
+# $Id: ins_mak,v 12.9 2020/12/08 09:05:57 tom Exp $
 #
 # Install the td_lib make include-file.  We adjust the symbols that refer
 # to the location of the include- and lib-directory.
 
-if test $# = 0 ; then
-	echo '? No INSTALL program given'
+failed() {
+	echo "? $*" >&2
 	exit 1
-fi
+}
+
+test $# = 0 && failed 'No INSTALL program given'
 PRG="$1"
 shift
 
-if test $# = 0 ; then
-	echo '? No DESTDIR given'
-	exit 1
-fi
+test $# = 0 && failed 'No DESTDIR given'
 DESTDIR=$1
 shift
 
-if test $# = 0 ; then
-	echo '? No DATADIR given'
-	exit 1
-fi
+test $# = 0 && failed 'No DATADIR given'
 CFGDIR=$1
 my_CFG=$1
 test -n "$DESTDIR" && my_CFG=`echo "$CFGDIR" | sed -e "s,$DESTDIR,,"`
 shift
 
-if test $# = 0 ; then
-	echo '? No LIBDIR given'
-	exit 1
-fi
+test $# = 0 && failed 'No LIBDIR given'
 LIBDIR=$1
 my_LIB=$1
 test -n "$DESTDIR" && my_LIB=`echo "$LIBDIR" | sed -e "s,$DESTDIR,,"`
 shift
 
-if test $# = 0 ; then
-	echo '? No INCLUDEDIR given'
-	exit 1
-fi
+test $# = 0 && failed 'No INCLUDEDIR given'
 INCDIR=$1
 my_INC=$1
 test -n "$DESTDIR" && my_INC=`echo "$INCDIR" | sed -e "s,$DESTDIR,,"`
 shift
 
-if test $# = 0 ; then
-	echo '? No SOURCE given'
-	exit 1
-fi
+test $# = 0 && failed 'No SOURCE given'
 
 SED=${TMPDIR-/tmp}/sed$$
-trap "rm -f $SED" 0 1 2 5 15
+trap 'rm -f "$SED"' EXIT INT QUIT TERM HUP
 
-cat >$SED <<EOF
-s@^TD_LIB[ 	]*=.*@TD_LIB = $my_LIB@
-s@^TD_INC[ 	]*=.*@TD_INC = $my_INC@
-s@^TD_CFG[ 	]*=.*@TD_CFG = $my_CFG@
+cat >"$SED" <<EOF
+/^TD_LIB[ 	]*=/s%=.*%= $my_LIB%
+/^TD_INC[ 	]*=/s%=.*%= $my_INC%
+/^TD_CFG[ 	]*=/s%=.*%= $my_CFG%
 EOF
 
-for SRC in $*
+for SRC in "$@"
 do
-	src=`basename $SRC`
-	TMP=${TMPDIR-/tmp}/$src
-	sed -f $SED $SRC > $TMP
-	eval $PRG $TMP $CFGDIR
-	rm -f $TMP
+	src=`basename "$SRC"`
+	if test -f "$SRC"
+	then
+		echo "installing $SRC in $CFGDIR"
+		TMP=${TMPDIR-/tmp}/$src
+		sed -f "$SED" "$SRC" > "$TMP"
+		eval "$PRG" "$TMP" "$CFGDIR"
+		rm -f "$TMP"
+	else
+		echo "..skipping $SRC"
+	fi
 done
